-- Tables used by goBabbyApp, named to match the original McGill DB2 schema.
-- Column names follow the Java queries (unquoted identifiers).
-- This file is valid on PostgreSQL and SQLite.

DROP TABLE IF EXISTS NOTES;
DROP TABLE IF EXISTS TESTS;
DROP TABLE IF EXISTS SETAPPOINT;
DROP TABLE IF EXISTS APPOINTMENTS;
DROP TABLE IF EXISTS ASSIGNEDMW;
DROP TABLE IF EXISTS PREGNANCIES;
DROP TABLE IF EXISTS COUPLE;
DROP TABLE IF EXISTS MOTHERS;
DROP TABLE IF EXISTS FATHERS;
DROP TABLE IF EXISTS MIDWIVES;
DROP TABLE IF EXISTS TECHNICIANS;

CREATE TABLE MIDWIVES (
    pracID   VARCHAR(16) PRIMARY KEY,
    email    VARCHAR(120),
    name     VARCHAR(80),
    phonenum VARCHAR(32)
);

CREATE TABLE MOTHERS (
    QCHCN         VARCHAR(32) PRIMARY KEY,
    MNAME         VARCHAR(80) NOT NULL,
    email         VARCHAR(120),
    dateofbirth   DATE,
    phonenum      VARCHAR(32)
);

CREATE TABLE FATHERS (
    fatherID VARCHAR(16) PRIMARY KEY,
    name     VARCHAR(80)
);

CREATE TABLE COUPLE (
    CID     VARCHAR(16) PRIMARY KEY,
    QCHCN   VARCHAR(32) NOT NULL,
    fatherID VARCHAR(16),
    FOREIGN KEY (QCHCN) REFERENCES MOTHERS (QCHCN)
);

CREATE TABLE PREGNANCIES (
    NTHPREG INTEGER NOT NULL,
    CID     VARCHAR(16) NOT NULL,
    PRIMARY KEY (NTHPREG, CID),
    FOREIGN KEY (CID) REFERENCES COUPLE (CID)
);

CREATE TABLE ASSIGNEDMW (
    pracID     VARCHAR(16) NOT NULL,
    NTHPREG    INTEGER NOT NULL,
    CID        VARCHAR(16) NOT NULL,
    IS_PRIMARY BOOLEAN NOT NULL,
    PRIMARY KEY (pracID, NTHPREG, CID),
    FOREIGN KEY (pracID) REFERENCES MIDWIVES (pracID),
    FOREIGN KEY (NTHPREG, CID) REFERENCES PREGNANCIES (NTHPREG, CID)
);

CREATE TABLE APPOINTMENTS (
    APPOINTID VARCHAR(16) PRIMARY KEY,
    NTHPREG   INTEGER NOT NULL,
    CID       VARCHAR(16) NOT NULL,
    ADATE     DATE NOT NULL,
    ATIME     TIME NOT NULL,
    FOREIGN KEY (NTHPREG, CID) REFERENCES PREGNANCIES (NTHPREG, CID)
);

CREATE TABLE SETAPPOINT (
    pracID    VARCHAR(16) NOT NULL,
    APPOINTID VARCHAR(16) NOT NULL,
    PRIMARY KEY (pracID, APPOINTID),
    FOREIGN KEY (pracID) REFERENCES MIDWIVES (pracID),
    FOREIGN KEY (APPOINTID) REFERENCES APPOINTMENTS (APPOINTID)
);

CREATE TABLE NOTES (
    NTIME     TIME NOT NULL,
    APPOINTID VARCHAR(16) NOT NULL,
    OBSERV    VARCHAR(1000) NOT NULL,
    PRIMARY KEY (NTIME, APPOINTID),
    FOREIGN KEY (APPOINTID) REFERENCES APPOINTMENTS (APPOINTID)
);

CREATE TABLE TECHNICIANS (
    TECHID   VARCHAR(16) PRIMARY KEY,
    name     VARCHAR(80),
    phonenum VARCHAR(32)
);

-- Column order matches INSERT INTO TESTS (SELECT testId, techId, appointId, ...)
CREATE TABLE TESTS (
    TESTID    VARCHAR(16) PRIMARY KEY,
    TECHID    VARCHAR(16) NOT NULL,
    APPOINTID VARCHAR(16) NOT NULL,
    PRESCDATE DATE NOT NULL,
    SAMPDATE  DATE,
    TESTTYPE  VARCHAR(80) NOT NULL,
    LABDATE   DATE,
    RESULT    VARCHAR(1000),
    FOREIGN KEY (APPOINTID) REFERENCES APPOINTMENTS (APPOINTID)
);
